### ISSUE TITLE
TypeError: Cannot read property 'date' of null

### ISSUE THREAD

**Issue by lukavia** [lgaticaq/node-nmea#2]
On the following line: 
$GPRMC,102939.000,A,4241.2649,N,02318.6959,E,2.87,50.45,260815,,*33
I get:
/home/lukav/Projects/gtsd/node_modules/node-nmea/lib/index.js:216
  var datetime = r.date + " " + r.time + " +00:00";
                  ^
TypeError: Cannot read property 'date' of null
    at Object.parse (/home/lukav/Projects/gtsd/node_modules/node-nmea/lib/index.js:216:19)
    at ProcessPack (/home/lukav/Projects/gtsd/server.js:67:30)
    at ProcessData (/home/lukav/Projects/gtsd/server.js:48:9)
    at Socket.<anonymous> (/home/lukav/Projects/gtsd/server.js:25:5)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)

The module is installed from npm

**Comment by lgaticaq** [comment]
Thanks for report errror
