### ISSUE TITLE
randomData() produces ReferenceError: Symbol is not defined

### ISSUE THREAD

**Issue by lukavia** [lgaticaq/node-nmea#4]
I tried to use the function getChecksum and discovered that it doesn't work. 
The problem is reviewed in randomData also: 
node
> var n = require('node-nmea');
undefined
> n.randomData();
ReferenceError: Symbol is not defined
    at getChecksum (/home/lukav/Projects/gtsd/node_modules/node-nmea/lib/index.js:40:36)
    at Object.randomData (/home/lukav/Projects/gtsd/node_modules/node-nmea/lib/index.js:308:18)
    at repl:1:3
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
>

**Comment by lgaticaq** [comment]
Resolve, add support to node >= 0.10.0
